### ISSUE TITLE
单例为什么要依赖于MonoBehavior呢？

### ISSUE THREAD

**Issue by sunny352** [CodeSuperHero/UnityFrame#1]
你的整体架构设计是打算围绕MonoBehavior来设计吗？虽然这种设计是Unity推荐的设计方式，但实际开发中使用这种方法的通常死的很惨，尤其是你这种连单例都要实例化一个GameObject然后挂载脚本的方式，其实我个人觉得没啥必要，直接创建单例对象，或者干脆使用静态方法也许更方便。

**Comment by CodeSuperHero** [comment]
居然有回复，很久不更新了，看到邮件通知...
这个工程可能会有很大变动，所以很久没更新了。
这里回答你的问题：单例分两种，一个是线程安全的C#单例类，一个是继承mono的单例类。

**Comment by sunny352** [comment]
没啥，我也是找找代码看到你这个的，因为我已经做了三四款游戏的基础架构设计了，越发觉得Unity的继承Mono的方式用起来非常不便，生存周期几乎不受代码控制，所以如果不是非要处理事件响应之类的需求 ，那就不会去继承Mono。至于线程安全的问题，除了自己写的网络库，Unity逻辑相关的东西都是单线程的，哪怕是开协程它也是单线程的，所以我这边单例的设计就没有专门为线程做过处理。
